package template.code;

import java.io.IOException;
import java.sql.SQLException;

import freemarker.template.TemplateException;

public class AutoGenerationDemo {

    public static void main(String[] args) throws ClassNotFoundException, SQLException, IOException, TemplateException {
        //数据库地址
        String url = "jdbc:mysql://47.100.233.253:3306/tst_member?useUnicode=true&characterEncoding=utf-8";
        //用户名
        String name = "root";
        //密码
        String passWord = "123456Qwe";
        //驱动
        String driver = "com.mysql.jdbc.Driver";
        //表名
        String tableName = "tst_information_report_reason";
        //我的模板路径 
        String templateDir = "/Users/sjb/Documents/project/bailiaohui/blh_java/tst/tst-common/autoTemplate";
        //生成文件路径
        String autoGeneratedFile = "/Users/sjb/Documents/project/bailiaohui/blh_java/tst/tst-common/auto";
        //实例化
        AutoGenerationJavaCode autoGenerationJavaCode = new AutoGenerationJavaCode(url, name, passWord, driver,
                tableName,autoGeneratedFile,templateDir);
        
        //调用生成java代码方法
        autoGenerationJavaCode.autoGenerationJavaCode();
    }

}
